apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: traefik
  namespace: monitoring
spec:
  endpoints:
  - interval: 15s
    port: "8082"
  selector: 
    matchLabels:
      k8s-app: traefik-ingress-lb
